version: "3.0"
services:
  dockerapp:
    build: . 
    container_name: dockerapp
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: redis:7.0.5
    container_name: dockerapp_redis

